# railway.toml  ── Config-as-Code solo acepta [build] y [deploy]
[build]
builder      = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand        = "uvicorn main:app --host 0.0.0.0 --port $PORT --log-level info"
healthcheckPath     = "/health"
healthcheckTimeout  = 300        # 5 min
restartPolicyType   = "ON_FAILURE"
restartPolicyMaxRetries = 10

